### ISSUE TITLE
Transfer to engineers.sg

### ISSUE THREAD

**Issue by sayanee** [engineersftw/website#34]
## Todo

- [x] Map http://api-webuild.7e14.starter-us-west-2.openshiftapps.com/events to `engineers.sg/api/events`
- [x] #31 Map http://api-webuild.7e14.starter-us-west-2.openshiftapps.com/cal to `engineers.sg/cal`
- [x] Add a note on `engineers.eg/events`

## References

- [Open Shift URLs](https://github.com/webuildorg/events/blob/master/README.md#tech-events-in-sg)

**Comment by sayanee** [comment]
It works 🎉 

![image](https://user-images.githubusercontent.com/413879/44441513-8025bb00-a5ff-11e8-8584-c7bcfabb5a0c.png)

**Comment by miccheng** [comment]
Published the `cal` link. And publishing the info on how to subscribe.
